package excecao;

public class ExceptionGenerico {

	public static void main(String[] args) {
		int[] numeros = {4, 8, 16, 32, 64, 128};
		int[] denom = {2, 0, 4, 8, 0};
		
		for(int i = 0; i < numeros.length; i++) {
			try {
				System.out.println(numeros[i] + " / " + denom[i] + " = " + numeros[i] / denom[i]);
			}
			//Podemos utilizar o Exception no lugar do Throwable, ele também é bem generico e é uma melhor prática
			catch(Exception ex) {
				System.out.println("EXCEÇÃO: " + ex.getMessage());
			}
			finally {
				System.out.println("\nEsta linha está no finally e por isto sempre será impressa após o try e os catch");
			}
		}

	}

}
